openapi: 3.0.1
info:
  title: 'Retry #2'
  description: ''
  version: '1.0'
servers:
  - url: https://apim-apiops-dev-eastus2-001.azure-api.net/rt2
paths:
  /429:
    post:
      summary: '429'
      description: '429'
      operationId: '429'
      requestBody:
        content:
          application/json:
            example:
              message: Hello
      responses:
        '200':
          description: ''
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]