openapi: 3.0.1
info:
  title: Star Wars
  description: API for retrieving info about the Star Wars universe
  version: '2023-09-17'
servers:
  - url: https://api-2.chrishou.se/2023-09-17
  - url: https://www.chrishou.se/2023-09-17
paths:
  /people:
    get:
      tags:
        - StarWars
      summary: Get People
      description: Gets a list of Star Wars people
      operationId: getPeople
      responses:
        '200':
          description: ''
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]