openapi: 3.0.1
info:
  title: bintest
  description: ''
  version: '1.0'
servers:
  - url: https://api-2.chrishou.se/bintest
  - url: https://www.chrishou.se/bintest
paths:
  /get:
    post:
      summary: POST
      operationId: post
      responses:
        '200':
          description: 
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]