openapi: 3.0.1
info:
  title: Star Wars
  description: API for retrieving info about the Star Wars universe
  version: 2024-09-17a
servers:
  - url: https://api-2.chrishou.se/2024-09-17a
  - url: https://www.chrishou.se/2024-09-17a
paths:
  /people:
    get:
      tags:
        - StarWars
      summary: Get People
      description: Gets a list of Star Wars people
      operationId: getPeople
      responses:
        '200':
          description: 'Success, contains a list of Star Wars people'
  '/people/{id}':
    get:
      summary: Get Person by Id
      description: Get Person by Id
      operationId: getPersonById
      parameters:
        - name: id
          in: path
          description: Identifier of person to return
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: 'Success, contains a Star Wars person'
          content:
            application/json: { }
        '404':
          description: Person not found
  /films:
    get:
      tags:
        - StarWars
      summary: Get Films
      description: Get Films
      operationId: get-films
      responses:
        '200':
          description: ''
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]